# Generated by Django 5.0.6 on 2024-07-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
