# Generated by Django 5.0.6 on 2024-07-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_purchasemodel_account'),
        ('account', '0004_alter_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
