# Generated by Django 5.0.6 on 2024-07-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
        ('auth_app', '0005_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.account'),
        ),
    ]
