# Generated by Django 5.0.6 on 2024-07-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_purchasemodel_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='transaction_type',
        ),
    ]
