# Generated by Django 5.0.6 on 2024-07-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customer_account_no_customer_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
