# Generated by Django 5.0.6 on 2024-07-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0006_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
