# Generated by Django 5.0.6 on 2024-07-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0007_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XLarge', 'XL'), ('XXLarge', 'XXL')], max_length=100, null=True),
        ),
    ]
