# Generated by Django 5.0.6 on 2024-07-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0014_remove_wishlist_product_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='cloth_product.product'),
        ),
    ]
