# Generated by Django 5.0.6 on 2024-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0015_remove_wishlist_product_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, to='cloth_product.product'),
        ),
    ]
