# Generated by Django 5.0.6 on 2024-08-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-size']},
        ),
    ]
