# Generated by Django 5.0.6 on 2024-08-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0018_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
