# Generated by Django 5.0.6 on 2024-08-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0019_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
