# Generated by Django 5.0.6 on 2024-08-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0021_sizemodel_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SizeModel',
        ),
    ]
