# Generated by Django 5.0.6 on 2024-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deposit', 'deposit')], max_length=50, null=True),
        ),
    ]
