# Generated by Django 5.0.6 on 2024-07-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_alter_transactionsmodel_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='balance',
        ),
    ]
