# Generated by Django 5.0.6 on 2024-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_remove_transactionsmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
